gemfile: StuHub/Gemfile
cache: bundler
language: ruby
rvm:
  - 2.2.3
addons:
  postgresql: "9.3"
install: 'cd StuHub && bundle install --deployment --jobs=3 --retry=3'
cache:
  directories:
  - vendor/bundle
before_script:
  - psql -c 'create database StuHub_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: 'bundle exec rake db:test:prepare && bundle exec rake'
